
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: abc123
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: CrmMentions_development

test:
  <<: *default
  database: CrmMentions_test

production:
  <<: *default
  database: CrmMentions_production
  username: CrmMentions
  password: <%= ENV['CRMMENTIONS_DATABASE_PASSWORD'] %>
